package com.voyager.airlines.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0040a1)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF0056d2)
val md_theme_light_onPrimaryContainer = Color(0xFFccd8ff)
val md_theme_light_secondary = Color(0xFFac3509)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFfe6f42)
val md_theme_light_onSecondaryContainer = Color(0xFF631800)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFf8f9fc)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFf8f9fc)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFe1e2e5)
val md_theme_light_onSurfaceVariant = Color(0xFF424654)
val md_theme_light_outline = Color(0xFF737785)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f3)
val md_theme_light_inverseSurface = Color(0xFF2e3133)
val md_theme_light_inversePrimary = Color(0xFFb2c5ff)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF0056d2)
val md_theme_light_outlineVariant = Color(0xFFc3c6d6)
val md_theme_light_scrim = Color(0xFF000000)

val surface_container_highest = Color(0xFFe1e2e5)
val surface_container_high = Color(0xFFe7e8eb)
val surface_container = Color(0xFFeceef0)
val surface_container_low = Color(0xFFf2f4f6)
val surface_container_lowest = Color(0xFFffffff)
val tertiary_fixed = Color(0xFF69ff87)
val on_tertiary_fixed = Color(0xFF002108)
val secondary_fixed = Color(0xFFffdbd0)
val on_secondary_fixed_variant = Color(0xFF852300)
val on_tertiary_fixed_variant = Color(0xFF00531e)
val tertiary_container = Color(0xFF006e2a)
val tertiary = Color(0xFF00531e)
val on_tertiary_container = Color(0xFF54f67a)
val primary_fixed_dim = Color(0xFFb2c5ff)
val outline = Color(0xFF737785)
